#smistare il traffico trra i microservizi
events {}

http {
    upstream user-manager {
        server user-manager:5001;
    }

    upstream data-collector {
        server data-collector:5002;
    }

    server {
        listen 80;

        # Rotte per lo User Manager
        location /register {
            proxy_pass http://user-manager;
        }

        location /login {
            proxy_pass http://user-manager;
        }

        # Rotte per il Data Collector
        location /add_interest {
            proxy_pass http://data-collector;
        }

        location /stats {
            proxy_pass http://data-collector;
        }
    }
}